<?php
namespace Estimate\Dao\Bean;

use Mouf\Database\TDBM\TDBMObject;

/*
 * This file has been automatically generated by TDBM.
 * DO NOT edit this file, as it might be overwritten.
 * If you need to perform changes, edit the QuestionsRangeBean class instead!
 */

/**
 * The QuestionsRangeBaseBean class maps the 'questions_range' table in database.
 * @dbTable questions_range
 */
class QuestionsRangeBaseBean extends TDBMObject 
{
	/**
	 * The getter for the "id" column.
	 *
	 * @dbType int
	 * @dbColumn id
	 * @return string
	 */
	public function getId(){
		return $this->__get('id');
	}
	
	/**
	 * The setter for the "id" column.
	 *
	 * @dbColumn id
	 * @param string $id
	 */
	public function setId($id) {
		$this->__set('id', $id);
	}
	
	/**
	 * The getter for the "text" column.
	 *
	 * @dbType string
	 * @dbColumn text
	 * @return string
	 */
	public function getText(){
		return $this->__get('text');
	}
	
	/**
	 * The setter for the "text" column.
	 *
	 * @dbColumn text
	 * @param string $text
	 */
	public function setText($text) {
		$this->__set('text', $text);
	}
	
	/**
	 * The getter for the "image" column.
	 *
	 * @dbType string
	 * @dbColumn image
	 * @return string
	 */
	public function getImage(){
		return $this->__get('image');
	}
	
	/**
	 * The setter for the "image" column.
	 *
	 * @dbColumn image
	 * @param string $image
	 */
	public function setImage($image) {
		$this->__set('image', $image);
	}
	
	/**
	 * The getter for the "answer" column.
	 *
	 * @dbType int
	 * @dbColumn answer
	 * @return string
	 */
	public function getAnswer(){
		return $this->__get('answer');
	}
	
	/**
	 * The setter for the "answer" column.
	 *
	 * @dbColumn answer
	 * @param string $answer
	 */
	public function setAnswer($answer) {
		$this->__set('answer', $answer);
	}
	
}
?>