<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace Estimate\Dao\Bean;
 
/**
 * The UserBean class maps the 'users' table in database.
 * @dbTable users
 *
 */
class UserBean extends UserBaseBean 
{

}