<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */
namespace Estimate\Dao;

/**
 * The QuestionsRangeDao class will maintain the persistance of QuestionsRangeBean class into the questions_range table.
 *
 * @Component
 * @dbTable questions_range
 */
class QuestionsRangeDao extends QuestionsRangeDaoBase
{

}