<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace Estimate\Dao\Bean;
 
/**
 * The QuestionsRangeBean class maps the 'questions_range' table in database.
 * @dbTable questions_range
 *
 */
class QuestionsRangeBean extends QuestionsRangeBaseBean 
{

}