<?php
namespace Estimate\Dao\Bean;

use Mouf\Database\TDBM\TDBMObject;

/*
 * This file has been automatically generated by TDBM.
 * DO NOT edit this file, as it might be overwritten.
 * If you need to perform changes, edit the UserBean class instead!
 */

/**
 * The UserBaseBean class maps the 'users' table in database.
 * @dbTable users
 */
class UserBaseBean extends TDBMObject 
{
	/**
	 * The getter for the "id" column.
	 *
	 * @dbType int
	 * @dbColumn id
	 * @return string
	 */
	public function getId(){
		return $this->__get('id');
	}
	
	/**
	 * The setter for the "id" column.
	 *
	 * @dbColumn id
	 * @param string $id
	 */
	public function setId($id) {
		$this->__set('id', $id);
	}
	
	/**
	 * The getter for the "login" column.
	 *
	 * @dbType string
	 * @dbColumn login
	 * @return string
	 */
	public function getLogin(){
		return $this->__get('login');
	}
	
	/**
	 * The setter for the "login" column.
	 *
	 * @dbColumn login
	 * @param string $login
	 */
	public function setLogin($login) {
		$this->__set('login', $login);
	}
	
	/**
	 * The getter for the "password" column.
	 *
	 * @dbType string
	 * @dbColumn password
	 * @return string
	 */
	public function getPassword(){
		return $this->__get('password');
	}
	
	/**
	 * The setter for the "password" column.
	 *
	 * @dbColumn password
	 * @param string $password
	 */
	public function setPassword($password) {
		$this->__set('password', $password);
	}
	
}
?>